#!/usr/bin/expect

if { [array names env TWOFACTOR_SECRET_PATH] != "" } {
	set expanded_secret_path [glob $env(TWOFACTOR_SECRET_PATH)]
	set secret [exec sed -n /^secret=/s///p $expanded_secret_path]
} else {
	set secret $env(TWOFACTOR_SECRET)
}

set token [exec oathtool --totp --base32 $secret]

log_user 0

spawn {*}$argv

expect {
	-re "\[Pp\]assword:\\s*" {
		send "$env(TWOFACTOR_PASSWORD)\n"
		exp_continue
	} -re "Verification code:\\s*" {
		send "$token\n"
		expect "\n"
	}
}

interact
catch wait result
exit [lindex $result 3]
